### ISSUE TITLE
Select layer behaviour

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#67] opened 2017-03-22 10:36 UTC
When the exposure/hazard/report layer is selected, we need to:
- Display note/label of what is selected
- When exposure is selected first, make “Run all the hazard layers” option available, or select all the hazard layers by default, then the user can unselect the hazard he doesn’t want to run.
- When it is impossible to do the analysis, make the corresponding layer unable to choose (for example, Indonesia Roads+Earthquake ). All valid combinations should work so this logic can use the list of possible combinations available in the backend InaSAFE.

**Comment by boney-bun** [comment] 2017-06-25 07:10
I can implement the first issue by putting these information on the legend.
the next two issues could be developed only if we have a good grasp on the data.
probably, we can start by making  a list of the appropriate layers combination. then, we would be able to verify the users selection against this list on the front end.

**Comment by gubuntu** [comment] 2017-06-25 12:11
atm selection is indicated by drawing the layer and showing its legend. If we work on more than one hazard layer then we could draw all of them and load their legends too. 

- add a layer toggle to the legend (on/off) next to the transparency slider. i.e. a layer can still be selected and in the legend but you can choose to switch it off if the map is too busy. 
- add a selection toggle to the hazard and exposure layer lists. atm you just see filtered layer list. I propose adding a checkbox so that the user can select more than one and always see which ones are selected. 
- deselect a layer if it no longer matches the spatial filter. 
- if we do item three, what if someone selects a global exposure layer? That means running all hazards against it. I think we need to implement automated running and caching before doing this. So analysis get run once and saved, then if someone tries the same one again, it just says 'already done' unless the data or metadata have changed. 
- what about multiple exposures? multiple exposures AND multiple hazards?
- are analysis filtered by location and selected hazard and exposure combinations?

...there's lots of new functionality in here so it should be broken into smaller issues and discussed more. Don't try to implement till after launch.

**Comment by boney-bun** [comment] 2017-08-02 15:25
we could see which layers are being selected in the legend now.
but it only restricts a pair of hazard and exposure layers.
@gubuntu @lucernae  i have one question: does inasafe support multiple hazard and exposure layers?

**Comment by gubuntu** [comment] 2017-08-05 16:34
@boney-bun please split into multiple issues then close this one. 

and capture our discussion from a few days ago before it becomes stale, in which there were clear instructions about how to proceed and which issues to work on now.

no InaSAFE does not support multiple hazard and exposure layers

**Comment by gubuntu** [comment] 2017-08-10 12:36
@boney-bun please finish complying with above instruction

**Comment by boney-bun** [comment] 2017-08-12 17:55
the issue is split into kartoza/geosafe#214, kartoza/geosafe#215, kartoza/geosafe#216, kartoza/geosafe#217.
i'll close this issue now.

**Closed as completed by boney-bun** 2017-08-12 17:55 UTC
Labels: WBExtension, UI/UX
