### ISSUE TITLE
Migrate GeoSAFE to InaSAFE Headless v4

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#284] opened 2018-03-09 04:48 UTC
We are going to use InaSAFE Headless v4 for the new GeoSAFE, This will include changes to migrate:

- Changes in celery task name
- Changes in UI/UX, such as, there will be aggregation layer

There might be several features to add, but for now we can make it work with the new headless first.

**Comment by gubuntu** [comment] 2018-05-08 07:03
duplicate of #53

**Closed as completed by gubuntu** 2018-05-08 07:03 UTC
Labels: help wanted
