### ISSUE TITLE
Custom analysis extent in geosafe analysis

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#166] opened 2017-06-27 15:30 UTC
# Problem
Since now we restricting the analysis to finish within ten minutes and that celery stops the running process. Why can we not create a [bounding box](http://osmz.ru/bbox/) that appears on the screen where a user can then drag that on the screen or resize it to make it smaller and run an analysis. 

This will make sure that all analysis that runs will complete. I do not see any reason to proceed with an analysis that is huge and will not finish under the time threshold given for.

We could use [leaflet](https://github.com/kajic/leaflet-locationfilter)

**Comment by lucernae** [comment] 2017-06-27 15:43
Yes, sorry @NyakudyaA , We don't have the UI at the moment, but you could limit the analysis bounding box by zooming in, the bounding box is using the map extent.
I'm planning to create the UI but currently focusing on another issue such as allowing user to update QML files.

Rectangle UI is a nice have for now (because we can already limit the extent using map extent).
@boney-bun if there's no more priority tasks, maybe you could handle it?

The process would be:

1. Create another leaflet plugin (or use existing one if possible) to draw extent on the map
2. Replace GeoSAFE logic to use this extent instead of map extent

The backend logic were already done, so we need only to provide the interaction.

**Comment by gubuntu** [comment] 2017-06-27 15:57
don't work on this now, @boney-bun just communicate to the user that they can zoom in to decrease the analysis extent.

**Comment by lucernae** [comment] 2017-06-28 18:22
I just realized from @NyakudyaA 's gif, that we can use shift drag to draw rectangle and we instantly zoom in! Very useful.

**Comment by gubuntu** [comment] 2017-07-06 12:00
duplicate of #111

**Closed as completed** 2017-07-06 12:00 UTC
Labels: question
