### ISSUE TITLE
The “Legend” description is out of column layout

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#115] opened 2017-05-14 15:03 UTC

**Comment by boney-bun** [comment] 2017-06-25 08:25
we need to make a compromise decision regarding this problem.
if we don't restrict the number of characters for the description, it would never enough space on the UI.
in the short term, i'm thinking of two possible solutions:
* use a smaller  font size on the legend
   cons: require extra effort for the users reading a long description 
* expand the legend area on the UI.
   cons: it may take up space for a smaller screen resolution.

**Comment by gubuntu** [comment] 2017-06-25 11:55
please don't work on backlog issues. First finished in progress and ready issues. 

Especially one like this that needs more information or discussion. 

Can you (@boney-bun) actually find a case where this is an issue? I think it was for a layer view, not analysis view. And I can't find an example. So if you can't either then you can close it.

**Comment by boney-bun** [comment] 2017-07-06 16:58
i'll close this ticket as it duplicate of #180.

**Closed as completed by boney-bun** 2017-07-06 16:58 UTC
Labels: bug, WBExtension
