### ISSUE TITLE
Hazard and exposure layer extents are not filtering properly 

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#414] opened 2018-10-29 14:28 UTC
# Problem

Filtering is not happening properly for hazard/exposure layer. 
![screenshot 2018-10-29 at 16 19 48](https://user-images.githubusercontent.com/2510900/47656240-607ab800-db97-11e8-9680-552a5a7d65be.png)

I assumed the extents would intersect somehow but they seem to be in totally different places.
![screenshot 2018-10-29 at 16 26 35](https://user-images.githubusercontent.com/2510900/47656295-81430d80-db97-11e8-9379-c3c8acef0a65.png)

**NB** This only occurs when a user is not logged in

# Solution
Fix

**Comment by myarjunar** [comment] 2018-10-29 15:03
Does this relate to the previous extent problem @boney-bun ? Since the problem is with the layer extent, I will re-assigned this to @boney-bun . cc @lucernae

**Comment by boney-bun** [comment] 2018-10-30 06:34
i don't fully understand the problem.
the use case is:
1. select `Tanzania Health Facilities` from Exposure section.
2. then, we suppose to select the Hazard section. The Hazard section was disabled to show that no corresponding Hazard layers with the selected Exposure layer.
The Exposure layers was still highlighted to indicate what a user has chosen previously (green colour).

i think this is the expected behaviour. right?

**Comment by NyakudyaA** [comment] 2018-10-30 06:38
> i don't fully understand the problem.
> the use case is:
> 
> 1. select `Tanzania Health Facilities` from Exposure section.
> 2. then, we suppose to select the Hazard section. The Hazard section was disabled to show that no corresponding Hazard layers with the selected Exposure layer.
>    The Exposure layers was still highlighted to indicate what a user has chosen previously (green colour).
> 
> i think this is the expected behaviour. right?

@boney-bun you are doing it the other way round. Select floods as a hazard layer and it zooms to Mozambique and shows that there is an exposure layer. Now select the exposure layer then it zooms out and deselects the hazard layer. If these two layers were not in the same geographical extent why are they appearing in each other's extent?

Mozambique layers should not be mixed with Tanzania stuff unless the first selected layer is larger than the extent of Mozambique and encroaches Tanzania.

I guess it also comes to the question of optimising workflows. Which one should be selected first just to make a user aware of the workflow but regardless I think the extent should be correct whether a user selects aggregation first.

**Comment by NyakudyaA** [comment] 2018-10-30 07:47
@gubuntu  can you comment on the following scenario we have uncovered.

* Currently it seems the analysis page filters layers based on the extent of the map. This allows a user to zoom in and out and the layers change based on this extent which works well.

* If a user toggles full screen then the map extent changes and this results in hazard/exposure layers showing up in the list which are not in the same geographical extent.
Example: If I select a hazard layer for Mozambique and I navigate to select the exposure when in full-screen mode. I also see exposure layers for Tanzania because we are using the map extent to filter layers.

I think we should be using the following scenario.

* If a user navigates to the analysis page the default filter uses map extent which is fine as is.
* If a user zooms in and out using the mouse it is still fine to filter based on the map extent.
* If a user selects a hazard layer then we should filter layers based on the bounding box of the layer regardless of the map extent. Because currently this is being affected by the map extent.

**Comment by gubuntu** [comment] 2018-10-31 06:42
@boney-bun I agree with @NyakudyaA's points. Once a user has selected any hazard, exposure or aggregation layer, the others should be filtered based on their selection.

**Closed as completed** 2018-11-07 10:20 UTC
Labels: bug
