### ISSUE TITLE
Reskin Interface

### ISSUE THREAD

**Issue by carina1000** [kartoza/geosafe#352] opened 2018-09-20 08:28 UTC
# Problem

We need to reskin GeoNode with INCG colours

# Solution

[GeoSAFE_Geonode.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46cf919510a3a58cb0ceba4caa52f4916b0a65633b0ba92e7391a172fd1723005d0b46fa150c5e11f9ac897ef4b63c76de5b5fe9d47f4366846c4ff8e7df46f554f832815d84b1b68b49c3ef3926e58a8a4e361a040ac4.pdf)

I have put all the assets you'd need into this folder: https://drive.google.com/drive/u/1/folders/1yL2_ZFT30Trf2f2j89LdSmIlAIIomECL?ogsrc=32

I would like to call and talk to you before you start implementing these designs!!

**Comment by gubuntu** [comment] 2018-09-20 08:43
duplicate of https://github.com/kartoza/geonode/issues/420

**Closed as completed by gubuntu** 2018-09-20 08:43 UTC
