### ISSUE TITLE
optimise osm buildings rendering

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#532] opened 2019-03-19 19:22 UTC
it's slow, sometimes timing out and sometimes 503

see what you can do with PostGIS config, QGIS config, styles, etc.

for the style, please make points way smaller (just dots not circles) especially at smaller scales.  The points / dots should not be bigger than the building polygons (which they are at the moment). And switch on the polygon layer one zoom level earlier.

**Comment by NyakudyaA** [comment] 2019-03-22 12:03
This was being caused by the data using the wrong extent. Now it's fixed in the database they should not be this issue
![geo-ext](https://user-images.githubusercontent.com/2510900/54821536-21b2df00-4cab-11e9-8baa-6daee6fbfcf7.png)

**Closed as completed by NyakudyaA** 2019-03-22 12:03 UTC
