### ISSUE TITLE
analysis results wrong or difficult to understand

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#434] opened 2018-11-03 13:52 UTC
1. I did this analysis with aggregation and there's no aggregation breakdown. Also, is 'total roads' just the length within the aggregation areas?
  a. I'd like to refer to the analysys with a 'share' url  - how do I do that?
1. how can total roads = roads affected? There are definitely some sections of rail/road that do not intersect flood polygons
1. to the user, 'dry' and 'not exposed'  mean the same thing. There's no 'dry' class in the hazard so where does that come from?
1. The Save checkbox is redundant if the user chose 'Save' in the previous dialogue. Rather remove the Save option from the previous dialogue and leave this checkbox.
![Screenshot 2018-11-02 at 22.06.10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7956e32a64c5b17af1122d4f5e5f5cb053181d1ba6acda6fb4bc2e75820d09b9d93b0b20c76814f9b8d74dbf01bc748c1b81b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fc95af348e34d55a2163671ab.png)

relataed to #437

**Comment by myarjunar** [comment] 2018-11-06 16:36
1. 
       - no aggregation breakdown might be caused by the faulty InaSAFE keywords ( see #433 )
       - yes, `total roads` is the length of roads within the analysis/aggregation area
       - we can easily add a share button on the pop-up report and linked to related analysis page. but there might be a problem with layer permission for user viewing that analysis anonymously.

2. fixed in #436 
3. there must be a dry or wet class because it uses `flood_hazard_classes` as defined here https://github.com/inasafe/inasafe/blob/develop/safe/definitions/hazard_classifications.py#L490. I think Flood Map keyword is also incorrect, confused between dry and wet. CMIIW
4. Will not be redundant id the user choose `save` in the previous dialog because it will be automatically checked, vice versa.

**Comment by NyakudyaA** [comment] 2018-11-14 13:30
I have tested this and will close this as most of the issues have been addressed. The only exception is to have the share button. I will close this and open the share button as a separate issue in the backlog.
#469

**Closed as completed by NyakudyaA** 2018-11-14 13:30 UTC
Labels: bug
