### ISSUE TITLE
Find a way to reliably monitor celery task and worker status

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#136] opened 2017-06-20 10:00 UTC
We can use flower to query the status of tasks.

**Comment by gubuntu** [comment] 2017-06-22 11:03
isn't this a duplicate of https://github.com/kartoza/docker-geosafe/issues/18?

**Comment by lucernae** [comment] 2017-07-06 12:25
I still considered flower as a `nice to have`. If we're able to use rancher we might not need this. We'll just use rancher to restart the worker. Also, I found out that task status can be queried easily programmatically and recently used this to restart/cancel the task. 
However, there is still some problem with InaSAFE worker randomly killed because InaSAFE headless uses QGIS Server in a headless way, and QGIS seems didn't properly handled/expect that it will be used in a multithreaded graphical way. When the graphics buffer thread died we don't have any mechanism to detect this within the code.
Relevant article for possible workaround:
https://groups.google.com/forum/#!topic/celery-users/fzFqCMID7sU

**Comment by lucernae** [comment] 2017-07-06 12:30
> isn't this a duplicate of kartoza/docker-geosafe#18?

That's ok, it tries to address a different problem. In kartoza/docker-geosafe#18 the issue is about integrating flower in the container to monitor celery tasks from geonode, geosafe, and inasafe-headless.
In this issue, the topic is to implement some code to query the task status from this flower instance.
After more research, I found out that celery have a native way to query these task status, programmatically and I'm using it now.
We still have some problem to detect the above case (graphics buffer thread died).
So, it's probably better if I change the title.

**Comment by gubuntu** [comment] 2017-08-10 12:20
@lucernae will this be done during August? If not please move back to backlog

**Comment by gubuntu** [comment] 2018-05-08 09:58
@lucernae has Rancher made this redundant? Status?

**Comment by gubuntu** [comment] 2018-10-10 06:23
@lucernae I'm assuming I can close this, please reopen and comment if I shouldn't have.

**Closed as completed by gubuntu** 2018-10-10 06:23 UTC
Labels: performance+scaling
