### ISSUE TITLE
Add option to zoom to full extent

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#25] opened 2016-12-21 13:40 UTC
# Problem

The initial extent in geosafe is the whole world. When a user selects an exposure layer he is immedially redirected to the extent of his exposure. There is no button that allows him to return to the extent of the world.
![zoom](https://cloud.githubusercontent.com/assets/2510900/21391280/aad750d0-c793-11e6-8e2b-79d3ce96eef8.png)

# Solution

Add icons and functionality to zoom to full extent.

**Comment by gubuntu** [comment] 2017-02-15 08:04
duplicate of #43

**Closed as completed** 2017-02-15 08:04 UTC
